{{- $scenario := .Values.scenario -}}
{{- $image := .Values.image -}}
{{- $scope := .Values.scope -}}
{{- $stats := .Values.stats -}}
{{- $sensor := .Values.sensor -}}
{{- $key := .Values.key -}}
{{- $api_url := .Values.api_url -}}
{{- $api_key := .Values.api_key -}}
{{- $api_secret := .Values.api_secret -}}
{{- $proxy := .Values.proxy -}}
{{ range $shipname, $ship := .Values.ships }}
{{- $binary_name := $ship.binary_name | default "ship" -}}
kind: Deployment
apiVersion: apps/v1
metadata:
    name: {{ $shipname }}
    labels:
        scenario: {{ $scenario }}
spec:
    replicas: {{ $ship.replicas }}

    selector:
        matchLabels:
            scenario: {{ $scenario }}
            ship: {{ $shipname }}
    template:
        metadata:
            labels:
                scenario: {{ $scenario }}
                ship: {{ $shipname }}
        spec:
            containers:
                - name: ship
                  image: {{ $image | default "bottle:latest" }}
                  command: ["/bin/sh", "-c", "./launch_ship.sh {{ $binary_name }} {{ $key }} {{ $proxy }}"]
                  lifecycle:
                    preStop:
                        exec:
                          command: ["/bin/sh","-c","killall -SIGUSR1 {{ $binary_name }}; sleep 4"]
                  securityContext:
                    capabilities:
                        add:
                            - SYS_PTRACE
                            - NET_ADMIN
                            - NET_RAW
                  env:
                    {{- if $proxy  }}
                    - name: HTTPS_PROXY
                      value: {{ $proxy }}
                    {{- end }}
                    - name: BOTTLE_SCOPE
                      value: {{ $scope | default "Default"}}
                    - name: BOTTLE_SCENARIO
                      value: {{ $scenario }}
                    - name: BOTTLE_SHIP
                      value: {{ $shipname }}
                    - name: BOTTLE_STATS
                      value: {{ $stats | default "false" | toString | quote }}
                    - name: BOTTLE_SENSOR
                      value: {{ $sensor | default "true" | toString | quote }}
                    - name: BOTTLE_API_URL
                      value: {{ $api_url }}
                    - name: BOTTLE_API_KEY
                      value: {{ $api_key }}
                    - name: BOTTLE_API_SECRET
                      value: {{ $api_secret }}
                  volumeMounts:
                    - mountPath: /etc/ship
                      name: config
            volumes:
                - name: tet
                  emptyDir: {}
                - name: config
                  configMap:
                    name: {{ $scenario }}-config
                    items:
                        - key: {{ $shipname }}
                          path: conf.yaml
---
{{end}}